/* js/config.js */
// Configuração do Firebase
export const firebaseConfig = {
    apiKey: "AIzaSyCqJ3D_bv-8UmnwGAk2n8qKb_EMLofUfys",
    authDomain: "olx---ads-ops-dashboard.firebaseapp.com",
    projectId: "olx---ads-ops-dashboard",
    storageBucket: "olx---ads-ops-dashboard.appspot.com",
    messagingSenderId: "149455998150",
    appId: "1:149455998150:web:3074fba78ddd3367f65bc7"
};

// Frases motivacionais
export const motivationalQuotes = [
  { text: "A suprema arte da guerra é derrotar o inimigo sem lutar.", author: "A Arte da Guerra" },
  { text: "Liderança é a capacidade de traduzir visão em realidade.", author: "O Monge e o Executivo" },
  { text: "Para se comunicar de forma eficaz, devemos perceber que somos todos diferentes na forma como percebemos o mundo.", author: "Poder Sem Limites" },
  { text: "Lembre-se de que a felicidade não depende de quem você é ou do que você tem, mas exclusivamente do que você pensa.", author: "Como Fazer Amigos e Influenciar Pessoas" },
  { text: "O sucesso normalmente vem para quem está ocupado demais para procurar por ele.", author: "Henry David Thoreau" },
  { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
  { text: "Tudo o que a mente humana pode conceber e acreditar, ela pode conquistar.", author: "Napoleon Hill" },
  { text: "A coragem é a resistência ao medo, o domínio do medo, não a ausência dele.", author: "Mark Twain" },
  { text: "A disciplina é a ponte entre metas e conquistas.", author: "Jim Rohn" },
  { text: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.", author: "Charles Darwin" },
  { text: "Grandes coisas nunca vêm da zona de conforto.", author: "Desconhecido" },
  { text: "A jornada de mil milhas começa com um único passo.", author: "Lao Tsé" },
  { text: "Se você não traçar seu próprio plano de vida, provavelmente cairá no plano de outra pessoa.", author: "Jim Rohn" },
  { text: "Acredite que você pode, e você já está no meio do caminho.", author: "Theodore Roosevelt" },
  { text: "O fracasso é apenas a oportunidade de começar de novo, desta vez de forma mais inteligente.", author: "Henry Ford" },
  { text: "Sonhe grande e ouse falhar.", author: "Norman Vaughan" },
  { text: "Não espere por oportunidades extraordinárias. Agarre ocasiões comuns e as torne grandes.", author: "Orison Swett Marden" },
  { text: "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.", author: "Zig Ziglar" },
  { text: "A sorte favorece a mente preparada.", author: "Louis Pasteur" },
  { text: "Você perde 100% dos tiros que não dá.", author: "Wayne Gretzky" },
  { text: "Faça o que você pode, com o que você tem, onde você está.", author: "Theodore Roosevelt" },
  { text: "Nunca é tarde demais para ser o que você poderia ter sido.", author: "George Eliot" },
  { text: "A melhor maneira de prever o futuro é criá-lo.", author: "Peter Drucker" },
  { text: "A ação é a chave fundamental para todo sucesso.", author: "Pablo Picasso" },
  { text: "A energia e a persistência conquistam todas as coisas.", author: "Benjamin Franklin" },
  { text: "Transforme suas feridas em sabedoria.", author: "Oprah Winfrey" },
  { text: "Se você quer alcançar a grandeza, pare de pedir permissão.", author: "Desconhecido" },
  { text: "As dificuldades preparam pessoas comuns para destinos extraordinários.", author: "C.S. Lewis" },
  { text: "A motivação é o que te faz começar. O hábito é o que te mantém no caminho.", author: "Jim Ryun" },
  { text: "Não tenha medo de desistir do bom para perseguir o ótimo.", author: "John D. Rockefeller" },
  { text: "Você nunca é velho demais para estabelecer uma nova meta ou sonhar um novo sonho.", author: "C.S. Lewis" },
  { text: "Acredite em milagres, mas não dependa deles.", author: "Immanuel Kant" },
  { text: "Seja a mudança que você deseja ver no mundo.", author: "Mahatma Gandhi" },
  { text: "O homem que move montanhas começa carregando pequenas pedras.", author: "Confúcio" },
  { text: "A persistência realiza o impossível.", author: "Provérbio Chinês" },
  { text: "Grandes feitos são compostos de pequenas ações.", author: "Lao Tsé" },
  { text: "A única maneira de fazer um excelente trabalho é amar o que você faz.", author: "Steve Jobs" },
  { text: "Arrisque mais do que os outros pensam ser seguro. Sonhe mais do que os outros pensam ser possível.", author: "Howard Schultz" },
  { text: "O futuro pertence àqueles que acreditam na beleza de seus sonhos.", author: "Eleanor Roosevelt" },
  { text: "Não importa quão devagar você vá, desde que você não pare.", author: "Confúcio" },
  { text: "A vida é 10% o que acontece com você e 90% como você reage a isso.", author: "Charles R. Swindoll" },
  { text: "Não se compare com ninguém neste mundo. Se o fizer, estará insultando a si mesmo.", author: "Bill Gates" },
  { text: "A diferença entre quem você é e quem você quer ser é o que você faz.", author: "Desconhecido" },
  { text: "Dificuldades reais podem ser superadas; são apenas as imaginárias que são invencíveis.", author: "Theodore V. Nail" },
  { text: "O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor é agora.", author: "Provérbio Chinês" },
  { text: "Não é sobre ter tempo, é sobre fazer tempo.", author: "Desconhecido" },
  { text: "A força não vem da capacidade física. Vem de uma vontade indomável.", author: "Mahatma Gandhi" },
  { text: "Coragem é a escada que o destino usa para chegar às estrelas.", author: "Desconhecido" },
  { text: "Nenhum mar calmo tornou-se um bom marinheiro.", author: "Provérbio Inglês" },
  { text: "Você só fracassa quando desiste.", author: "Desconhecido" },
  { text: "Sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { text: "Seja tão bom que não possam te ignorar.", author: "Steve Martin" },
  { text: "A mente é tudo. Você se torna aquilo que pensa.", author: "Buda" },
  { text: "Nunca confunda uma derrota com uma falha final.", author: "F. Scott Fitzgerald" },
  { text: "Grandes mentes discutem ideias, mentes medianas discutem eventos, mentes pequenas discutem pessoas.", author: "Eleanor Roosevelt" },
  { text: "A vitória pertence ao mais perseverante.", author: "Napoleão Bonaparte" },
  { text: "Se você está atravessando o inferno, continue andando.", author: "Winston Churchill" },
  { text: "A única limitação para o nosso amanhã são as nossas dúvidas de hoje.", author: "Franklin D. Roosevelt" },
  { text: "Coragem não é ausência de medo, é avançar apesar dele.", author: "Desconhecido" },
  { text: "Não viva para que a sua presença seja notada, mas para que a sua falta seja sentida.", author: "Bob Marley" },
  { text: "O maior prazer da vida é fazer o que as pessoas dizem que você não é capaz de fazer.", author: "Walter Bagehot" },
  { text: "Você nunca sabe a força que tem, até que sua única alternativa é ser forte.", author: "Bob Marley" },
  { text: "Não tenha medo da mudança. Coisas boas se vão para que melhores possam vir.", author: "Desconhecido" },
  { text: "A persistência é o combustível do sucesso.", author: "Desconhecido" },
  { text: "O que não provoca minha morte faz com que eu fique mais forte.", author: "Friedrich Nietzsche" },
  { text: "Jamais se desespere em meio às sombrias aflições de sua vida, pois das nuvens mais negras cai água límpida e fecunda.", author: "Provérbio Chinês" },
  { text: "A vida é feita de escolhas. Quando você dá um passo, o universo inteiro conspira a favor.", author: "Paulo Coelho" },
  { text: "Se você cair sete vezes, levante-se oito.", author: "Provérbio Japonês" },
  { text: "A vida começa no final da sua zona de conforto.", author: "Neale Donald Walsch" },
  { text: "A persistência pode transformar o fracasso em um extraordinário sucesso.", author: "Matt Biondi" },
  { text: "Grandes conquistas nascem de grandes sacrifícios.", author: "Desconhecido" },
  { text: "Não espere por circunstâncias ideais. Comece onde você está.", author: "Napoleon Hill" },
  { text: "Quem ousa vence.", author: "Provérbio" },
  { text: "Quanto maior a dificuldade, maior a glória.", author: "Cícero" },
  { text: "Não é a carga que o derruba, mas a maneira como você a carrega.", author: "Lou Holtz" },
  { text: "A adversidade desperta em nós capacidades que estavam adormecidas.", author: "Horácio" },
  { text: "Cada dificuldade que você enfrenta é um degrau a mais para o sucesso.", author: "Desconhecido" },
  { text: "O otimismo é a fé em ação. Nada se pode levar a efeito sem otimismo.", author: "Helen Keller" },
  { text: "A vitória está reservada para aqueles que estão dispostos a pagar o preço.", author: "Sun Tzu" },
  { text: "Seja a inspiração que você procura.", author: "Desconhecido" },
  { text: "A disciplina vence o talento, quando o talento não tem disciplina.", author: "Desconhecido" },
  { text: "A chave do sucesso é começar antes de estar pronto.", author: "Marie Forleo" },
  { text: "Só erra quem tenta.", author: "Desconhecido" },
  { text: "Quem vence sem riscos triunfa sem glória.", author: "Pierre Corneille" },
  { text: "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.", author: "Winston Churchill" },
  { text: "Nunca reclame do vento. Aprenda a usar as velas.", author: "Desconhecido" },
  { text: "Seja você mesmo, todos os outros já existem.", author: "Oscar Wilde" },
  { text: "Coragem é saber o que não temer.", author: "Platão" },
  { text: "Nada acontece até que algo se mova.", author: "Albert Einstein" },
  { text: "A excelência não é um feito, mas um hábito.", author: "Aristóteles" },
  { text: "A vida é uma aventura ousada ou não é nada.", author: "Helen Keller" },
  { text: "Quem quer vencer um obstáculo deve armar-se da força do leão e da prudência da serpente.", author: "Píndaro" },
  { text: "A fé em si mesmo é o primeiro segredo do sucesso.", author: "Ralph Waldo Emerson" },
  { text: "Não espere resultados diferentes fazendo sempre as mesmas coisas.", author: "Albert Einstein" },
  { text: "A vitória está sempre ao alcance de quem luta com determinação.", author: "Desconhecido" },
  { text: "A vida recompensa a ação, não a intenção.", author: "Desconhecido" },
  { text: "Não importa quantos erros você cometa, você ainda está à frente de quem não tentou.", author: "Tony Robbins" },
  { text: "Faça hoje o que outros não querem, e amanhã viverá o que outros não podem.", author: "Desconhecido" },
  { text: "Coragem é não deixar que o medo controle suas ações.", author: "Desconhecido" },
  { text: "A determinação de hoje é o sucesso de amanhã.", author: "Desconhecido" },
  { text: "Trabalhe em silêncio e deixe que o sucesso faça barulho.", author: "Frank Ocean" },
  { text: "Um objetivo sem plano é apenas um desejo.", author: "Antoine de Saint-Exupéry" },
  { text: "O segredo do sucesso está na constância do propósito.", author: "Benjamin Disraeli" },
  { text: "Nunca desista de um sonho só por causa do tempo que levará para realizá-lo. O tempo vai passar de qualquer forma.", author: "Earl Nightingale" },
  { text: "A ação cura o medo.", author: "David J. Schwartz" },
  { text: "O impossível é apenas uma opinião.", author: "Paulo Coelho" },
  { text: "Seja forte o bastante para deixar ir e sábio o bastante para esperar o que merece.", author: "Desconhecido" },
  { text: "A força de vontade deve ser mais forte que a habilidade.", author: "Muhammad Ali" },
  { text: "Toda realização começa com a decisão de tentar.", author: "Gail Devers" },
  { text: "Não espere o momento perfeito. Pegue o momento e o torne perfeito.", author: "Zoey Sayward" },
  { text: "Se você quer algo que nunca teve, precisa estar disposto a fazer algo que nunca fez.", author: "Thomas Jefferson" },
  { text: "O sucesso é construído por aqueles que não têm medo de falhar.", author: "Desconhecido" },
  { text: "A vida é feita de pequenos passos, não de grandes saltos.", author: "Desconhecido" },
  { text: "Nunca é tarde demais para recomeçar e escrever um novo final.", author: "Desconhecido" },
  { text: "As grandes vitórias são conquistadas com paciência e determinação.", author: "Desconhecido" },
  { text: "Não tenha medo de começar de novo. É uma chance de refazer melhor desta vez.", author: "Desconhecido" },
  { text: "O segredo não é correr atrás das borboletas, mas cuidar do jardim para que elas venham até você.", author: "Mario Quintana" },
  { text: "A vida é curta demais para esperar pelo amanhã.", author: "Desconhecido" },
  { text: "Não existe ascensor para o sucesso, você precisa subir as escadas.", author: "Zig Ziglar" },
  { text: "Cada segundo é tempo para mudar tudo para sempre.", author: "Charles Chaplin" },
  { text: "A verdadeira motivação vem de realizar, desenvolver e expressar seu potencial.", author: "Stephen Covey" },
  { text: "Quanto mais difícil a batalha, mais doce é a vitória.", author: "Les Brown" },
  { text: "Seja a voz que encoraja, não o eco que desanima.", author: "Desconhecido" },
  { text: "A vida é feita de coragem para arriscar e sabedoria para esperar.", author: "Desconhecido" },
  { text: "Não limite seus desafios. Desafie seus limites.", author: "Desconhecido" },
  { text: "O amanhã depende das escolhas que você faz hoje.", author: "Desconhecido" },
  { text: "Seja grato pelo que tem enquanto luta pelo que deseja.", author: "Desconhecido" },
  { text: "Você é mais forte do que imagina e capaz de mais do que pensa.", author: "Desconhecido" },
  { text: "A felicidade não é algo pronto. Ela vem de suas próprias ações.", author: "Dalai Lama" },
  { text: "Grandes sonhos requerem grandes sacrifícios.", author: "Desconhecido" },
  { text: "Acredite: você já está mais perto do que imagina.", author: "Desconhecido" },
  { text: "O esforço de hoje é o sucesso de amanhã.", author: "Desconhecido" },
  { text: "Nenhum obstáculo é grande demais quando sua vontade de vencer é maior.", author: "Desconhecido" },
  { text: "A constância transforma pequenas conquistas em grandes vitórias.", author: "Desconhecido" },
  { text: "O primeiro passo não leva você onde quer ir, mas tira você de onde está.", author: "Desconhecido" },
  { text: "O único lugar onde sucesso vem antes do trabalho é no dicionário.", author: "Vidal Sassoon" },
  { text: "Quem não luta pelo que quer, aceita o que vier.", author: "Desconhecido" },
  { text: "Persistência é acreditar no impossível até que se torne possível.", author: "Desconhecido" },
  { text: "Você não é derrotado quando perde. Você é derrotado quando desiste.", author: "Desconhecido" },
  { text: "A vida é feita de superações diárias.", author: "Desconhecido" },
  { text: "Nunca subestime o poder da sua mente e do seu coração.", author: "Desconhecido" },
  { text: "Seja o motivo pelo qual alguém acredita na bondade das pessoas.", author: "Desconhecido" },
  { text: "A vitória começa com a decisão de tentar.", author: "Desconhecido" },
  { text: "Sucesso não é sorte, é esforço e dedicação.", author: "Desconhecido" },
  { text: "Você pode ter resultados ou desculpas. Nunca os dois.", author: "Arnold Schwarzenegger" },
  { text: "Quem acredita sempre alcança.", author: "Desconhecido" }
];
